---
- name: Configure Ubuntu
  hosts: dev
  vars_files:
    - ../host_vars.yaml
  # vars:
#    host_username: ubuntu
    # authorized_keys: '{{ lookup("file", "../id_rsa.pub") }}'
  handlers:
    - name: Restart sshd
      service: name=sshd state=restarted
      become: true
  tasks:
    - name: Install base system packages
      package:
        name: '{{item}}'
        state: latest
      loop:
        - curl
        - htop
        - unzip
        - wget
        - zip
        - colordiff
      tags: ['base_packages', 'packages']
      become: true

    - name: Install dev packages
      package:
        name: '{{item}}'
        state: latest
      loop:
        - git
        - ffmpeg
        - terraform
        - python3
        - python3-pip
      become: true
      tags: ['dev_packages', 'packages']

    - name: Remove not-needed packages
      package:
        name: '{{item}}'
        state: absent
      loop:
        - chromium
      tags: ['remove_packages']
      become: true

    - name: Ensure user dot files
      copy:
        src: '{{item.src}}'
        dest: '{{item.dest}}'
        mode: '0600'
        owner: '{{host_username}}'
        group: '{{host_username}}'
      # Add user dot files here 
      loop:
        - { src: dots/.wgetrc, dest: '/home/{{host_username}}/.wgetrc' }
        - { src: dots/.gitignore, dest: '/home/{{host_username}}/.gitignore' }
        - { src: dots/.curlrc, dest: '/home/{{host_username}}/.curlrc' }
        - { src: dots/bash_aliases, dest: '/home/{{host_username}}/.bash_aliases' }
      tags: ['user_dots', 'dots']

    - name: Ensure root dot files
      copy:
        src: '{{item.src}}'
        dest: '{{item.dest}}'
        mode: '0600'
        owner: root
        group: root
      # Add root dot files here
      loop:
        - { src: dots/wgetrc, dest: '/root/.wgetrc' }
        - { src: dots/curlrc, dest: '/root/.curlrc' }
      become: true
      tags: ['dots']

    - name: Ensure user files (from templates)
      template:
        src: '{{item.src}}'
        dest: '{{item.dest}}'
        mode: '0600'
        owner: '{{host_username}}'
        group: '{{host_username}}'
      loop:
        - { src: dots/authorized_keys, dest: '/home/{{host_username}}/.ssh/authorized_keys' }
        - { src: dots/authorized_keys, dest: '/home/{{host_username}}/.ssh/authorized_keys' }

    - name: Ensure default directories in home
      file:
        path: '{{item}}'
        state: directory
        mode: '0700'
        owner: '{{host_username}}'
        group: '{{host_username}}'
      loop:
        - '/home/{{host_username}}/dots'
        - '/home/{{host_username}}/playground'
      become: true
      tags: ['dir-structure']

    # Install python extra packages and ensure they are up to date.
    - name: Ensure pip3 packages
      pip:
        name: '{{item}}'
        executable: pip3
        state: latest
      loop:
        - ansible
        - awscli
        - pipenv
      become: true
