---
- name: Configure Store VM
  hosts: all
  vars_files:
    # - ../store_host_vars.yaml
    - vars/store_defaults.yml
  become: true
  vars:
    apt_retries: 15 
    apt_retry_delay: 10

  handlers:
    - name: Restart sshd
      service: name=sshd state=restarted
    - name: reload systemctl
      command: systemctl daemon-reload

  pre_tasks:
    - name: Install base system packages
      package:
        name: '{{item}}'
        state: latest
      loop:
        - curl
        - htop
        - unzip
        - wget
        - zip
        - colordiff
        - lsb-release
        - git
        - python3
        - python3-pip
        - glusterfs-client
        - glusterfs-server
      tags: ['base_packages', 'packages']
      become: true
      register: result
      until: result is not failed
      retries: '{{ apt_retries }}'
      delay: '{{ apt_retry_delay }}'
  
    - name: Update System
      when: update_system == true
      include_tasks: tasks/update_system.yml

    - name: Start and enable GlusterFS server service
      when: enable_glusterfs == true
      service:
        name: glusterd
        state: started
        enabled: yes

    - name: Mount External Network volumes
      when: 
        - mounts is defined
      include_tasks: tasks/mount_network_volumes.yml
    
    - name: Configure Store volumes
      when: 
        - volumes is defined       
      include_tasks: tasks/configure_volumes.yml
  
  tasks:
    - name: Ensure user dot files
      copy:
        src: '{{item.src}}'
        dest: '{{item.dest}}'
        mode: '0600'
        owner: '{{host_username}}'
        group: '{{host_username}}'
      loop:
        - { src: dots/.wgetrc, dest: '/home/{{host_username}}/.wgetrc' }
        - { src: dots/.gitignore, dest: '/home/{{host_username}}/.gitignore' }
        - { src: dots/.curlrc, dest: '/home/{{host_username}}/.curlrc' }
        - { src: dots/.bash_aliases, dest: '/home/{{host_username}}/.bash_aliases' }
      tags: ['user_dots', 'dots']

    - name: Ensure root dot files
      copy:
        src: '{{item.src}}'
        dest: '{{item.dest}}'
        mode: '0600'
        owner: root
        group: root
      loop:
        - { src: dots/.wgetrc, dest: '/root/.wgetrc' }
        - { src: dots/.curlrc, dest: '/root/.curlrc' }
      become: true
      tags: ['dots']

    - name: Ensure default directories in home
      file:
        path: '{{item}}'
        state: directory
        mode: '0700'
        owner: '{{host_username}}'
        group: '{{host_username}}'
      loop:
        - '/home/{{host_username}}/.ssh'

    - name: Ensure user files (from templates)
      template:
        src: '{{item.src}}'
        dest: '{{item.dest}}'
        mode: '0600'
        owner: '{{host_username}}'
        group: '{{host_username}}'
      loop:
        - { src: dots/authorized_keys, dest: '/home/{{host_username}}/.ssh/authorized_keys' }
   