---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
    owner: "{{ item.owner | default(default_volume_owner) }}"
    group: "{{ item.group | default(default_volume_group) }}"
  with_items: "{{ volumes }}"

- name: Configure Gluster volumes
  gluster_volume:
    state: "{{ item.config_state }}"
    name: "{{ item.name }}"
    brick: "{{ item.path }}"
    cluster: "{{ ansible_default_ipv4.address }}"
    host: "{{ ansible_default_ipv4.address }}"
    force: true
  become: true
  run_once: true
  failed_when: false
  loop: "{{ volumes }}"
  when:
    - item.type == 'glusterfs'

- name: Start Gluster volumes
  gluster_volume:
    state: "{{ item.start_state }}"
    name: "{{ item.name }}"
  become: true
  run_once: true
  failed_when: false
  loop: "{{ volumes }}"
  when:
    - item.type == 'glusterfs'
