---
- name: Install Git
  apt:
    name: git
    state: present
- name: Configure Git Name
  git_config:
    name: user.name
    value: "{{ git_user_name }}"
- name: Configure Git Email
  git_config:
    name: user.email
    value: "{{ git_email }}"