---
- name: Install Git
  ansible.builtin.apt:
    name: git
    state: present
- name: Configure Git Name
  community.general.git_config:
    name: user.name
    value: "{{ git_user_name }}"
- name: Configure Git Email
  community.general.git_config:
    name: user.email
    value: "{{ git_email }}"
