---
- name: Create directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(default_volume_owner) }}"
    group: "{{ item.group | default(default_volume_group) }}"
  with_items: "{{ volumes }}"

- name: Configure Gluster volumes
  gluster_volume:
    state: "{{ item.config_state }}"
    name: "{{ item.name }}"
    brick: "{{ item.path }}"
    cluster: "{{ ansible_default_ipv4.address }}"
    host: "{{ ansible_default_ipv4.address }}"
    force: yes
  become: true
  run_once: true
  ignore_errors: true
  loop: "{{ volumes }}"
  when:
    - item.type == 'glusterfs'

- name: Start Gluster volumes
  gluster_volume:
    state: "{{ gluster.start_state }}"
    name: "{{ gluster.name }}"
  become: true
  run_once: true
  ignore_errors: true
  loop: "{{ volumes }}"
  when:
    - item.type == 'glusterfs'