---
- name: Add GlusterFS GPG key
  apt_key:
    url: https://download.gluster.org/pub/gluster/glusterfs/9/rsa.pub 
    state: present

- name: Add GlusterFS APT repository
  become: true
  ansible.builtin.shell: |
    #!/bin/sh
    DEBID=$(grep 'VERSION_ID=' /etc/os-release | cut -d '=' -f 2 | tr -d '"')
    DEBVER=$(grep 'VERSION=' /etc/os-release | grep -Eo '[a-z]+')
    DEBARCH=$(dpkg --print-architecture)
    echo deb https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/${DEBID}/${DEBARCH}/apt ${DEBVER} main > /etc/apt/sources.list.d/gluster.list

- name: Install base system packages
  package:
    name: '{{item}}'
    state: latest
  loop:
    - glusterfs-client
    - glusterfs-server
  tags: ['glusterfs', 'packages']
  become: true
  register: result
  until: result is not failed
  retries: '{{ apt_retries }}'
  delay: '{{ apt_retry_delay }}'