---
- name: Download Code Server 
  become: true
  get_url:
    url: https://code-server.dev/install.sh
    dest: /tmp/install-code-server.sh
    mode: 'a+x'

- name: Install Code Server
  become: true
  command: bash +x /tmp/install-code-server.sh

- name: Configure Code Server - Bind Addr
  lineinfile:
    path: /home/{{host_username}}/.config/code-server/config.yaml
    regexp: '^bind-addr:'
    line: 'bind-addr: 0.0.0.0:8080'
    state: present

- name: Enable Code Server Service
  become: true
  systemd:
    name: code-server@{{host_username}}
    enabled: yes
    state: started