---
- name: Ensure mount directories
  file:
    path: "{{ item.mount_path }}"
    state: directory
    mode: '0755'
    owner: "{{ item.owner | default(default_volume_owner) }}"
    group: "{{ item.group | default(default_volume_group) }}"
  with_items: "{{ mounts }}"
  tags: ['dir-structure', 'mounts']

- name: Add GlusterFS volumes to fstab
  lineinfile:
    path: "/etc/fstab"
    line: "{{ item.server | default(default_glusterfs_server) }}:/{{ item.name }} {{ item.mount_path }} glusterfs defaults,_netdev 0 0"
    state: "{{ item.config_state | default('present') }}"
  when: 
    - item.type == "glusterfs"
    - enable_glusterfs == true
  with_items: "{{ mounts }}"
  tags: ['glusterfs', 'fstab']

- name: Add CIFS volumes to fstab
  lineinfile:
    path: "/etc/fstab"
    line : "//{{ item.server | default(default_cifs_server) }}/{{ item.name }} {{ item.mount_path }} cifs vers=3.0,credentials={{ item.credentials | default('/home/'~host_username~'/.cifscredentials') }},file_mode={{ item.file_mode | default('0755') }},dir_mode={{ item.dir_mode | default('0755') }},uid={{ item.owner | default(default_volume_owner) }},gid={{ item.group | default(default_volume_group) }},nofail 0 0"
    state: "{{ item.config_state | default('present') }}"
  when: 
    - item.type == "cifs"
    -  enable_cifs == true
  with_items: "{{ mounts }}"
  tags: ['cifs', 'fstab']

- name: Mount Volumes
  command: mount {{ item.mount_path }}
  when: item.mount == true
  with_items: "{{ mounts }}"
  tags: ['dir-structure', 'mount'] 

- name: Create Home User directory
  with_items: "{{ mounts }}"
  when: item.home_mount == true
  file:
    path: "{{ item.mount_path }}/{{ host_username | default('ubuntu') }}"
    state: directory
    mode: '0755'
    owner: '{{ host_username }}'
    group: '{{ host_username }}'
