---
- name: Ensure glusterfs home directories
  ansible.builtin.file:
    # Extract the last part of the mount name, which is the username
    path: "/home/{{ mount | regex_search('.+_.+_(.+)', '\\1') }}"
    state: directory
    mode: '0755'
    owner: '{{ host_username }}'
    group: '{{ host_username }}'
  loop: "{{ glusterfs_home_mounts_list }}"
  loop_control:
    loop_var: mount
  become: true
  tags: ['dir-structure', 'glusterfs', 'mounts', 'home']

- name: Add GlusterFS home volumes to fstab
  ansible.builtin.lineinfile:
    path: "/etc/fstab"
    line: "{{ glusterfs_server }}:/{{ mount }} /home/{{ mount | regex_search('.+_.+_(.+)', '\\1') }} glusterfs defaults,_netdev 0 0"
    state: present
  loop: "{{ glusterfs_home_mounts_list }}"
  loop_control:
    loop_var: mount
  become: true
  tags: ['dir-structure', 'glusterfs']

- name: Mount all
  ansible.builtin.command: mount -a
  become: true
  tags: ['dir-structure', 'glusterfs']
