---
- name: Ensure glusterfs mount directories
  file:
    path: "{{ item.mount_path }}"
    state: directory
    mode: '0755'
    owner: '{{item.owner}}'
    group: '{{item.group}}'
  with_items: "{{ mounts }}"
  tags: ['dir-structure', 'glusterfs', 'mounts']

- name: Add GlusterFS volumes to fstab
  lineinfile:
    path: "/etc/fstab"
    line: "{{ item.server }}:/{{ item.name }} {{ item.mount_path }} glusterfs defaults,_netdev 0 0"
    state: "{{ item.config_state }}"
  with_items: "{{ mounts }}"
  tags: ['dir-structure', 'glusterfs', 'fstab']

- name: mount all
  command: mount
  when: item.mount == true
  with_items: "{{ mounts }}"
  tags: ['dir-structure', 'glusterfs', 'mount-all'] 

- name: Create Home User directory
  with_items: "{{ mounts }}"
  when: item.home_mount == true
  file:
    path: "{{ item.mount_path }}/{{ host_username }}"
    state: directory
    mode: '0755'
    owner: '{{ host_username }}'
    group: '{{ host_username }}'
